[phases.setup]
aptPkgs = ["python3", "python3-pip", "ffmpeg"]

[phases.install]
cmds = [
  "pip3 install --break-system-packages --upgrade yt-dlp",
  "ln -sf /usr/local/bin/yt-dlp /usr/bin/yt-dlp || true"
]

[start]
cmd = "npm start"
